const axios = require('axios');
const Article = require('../models/article');
const Video = require('../models/video');

// Placeholder AI fallback function
async function getAIFallback(subtopic_id) {
  // Example: fetch similar content from other feeds
  // and generate AI summary (replace with OpenAI API later)
  const fallbackContent = [
    {
      title: 'AI Generated Article 1',
      url: 'https://example.com/ai-article-1',
      topic_id: null,
      subtopic_id,
      source: 'AI Fallback',
      published_at: new Date(),
      AI_summary: 'This article was generated by AI because feed was inactive.',
      tags: ['AI', 'Fallback']
    },
    {
      title: 'AI Generated Video 1',
      url: 'https://example.com/ai-video-1',
      topic_id: null,
      subtopic_id,
      source: 'AI Fallback',
      published_at: new Date(),
      AI_summary: 'This video was generated by AI because feed was inactive.',
      tags: ['AI', 'Fallback']
    }
  ];

  // Save AI fallback content to database
  for (const content of fallbackContent) {
    if (content.url.includes('video')) {
      await Video.create(content);
    } else {
      await Article.create(content);
    }
  }

  return fallbackContent;
}

module.exports = getAIFallback;
